BEGIN
   DBMS_OUTPUT.PUT_LINE('Session Timezone = ' || SESSIONTIMEZONE);
   DBMS_OUTPUT.PUT_LINE('Session Timestamp = ' || CURRENT_TIMESTAMP);
   DBMS_OUTPUT.PUT_LINE('DB Server Timestamp = ' || SYSTIMESTAMP);
   DBMS_OUTPUT.PUT_LINE('DB Timezone = ' || DBTIMEZONE);
   EXECUTE IMMEDIATE 'ALTER SESSION SET TIME_ZONE=DBTIMEZONE';
   DBMS_OUTPUT.PUT_LINE('DB Timestamp = ' || CURRENT_TIMESTAMP);
   -- Revert session time zone to local setting
   EXECUTE IMMEDIATE 'ALTER SESSION SET TIME_ZONE=LOCAL';
   DBMS_OUTPUT.PUT_LINE('-----------------------');
   DBMS_OUTPUT.PUT_LINE('DATE (Current Date) = ' || CURRENT_DATE);
   DBMS_OUTPUT.PUT_LINE('TIMESTAMP WITH TIME ZONE (Current Timestamp) = ' || CURRENT_TIMESTAMP);
   DBMS_OUTPUT.PUT_LINE('TIMESTAMP (Local Timestamp) = ' || LOCALTIMESTAMP);
   DBMS_OUTPUT.PUT_LINE('SYSDATE (Date) = ' || SYSDATE);
   DBMS_OUTPUT.PUT_LINE('TIMESTAMP WITH TIME ZONE (Systimestamp) = ' || SYSTIMESTAMP);
   DBMS_OUTPUT.PUT_LINE('DB Timezone = ' || DBTIMEZONE);
END;
/

