drop table person;
drop table preference;
drop table book;


CREATE TABLE person (
   name VARCHAR2(100),
   dob DATE
);

CREATE TABLE preference (
   person_name VARCHAR2(100),
   name VARCHAR2(100),
   type VARCHAR2(100)
);

CREATE TABLE book (
  isbn VARCHAR(100) NOT NULL PRIMARY KEY,
  title VARCHAR2(200),
  summary VARCHAR2(2000),
  author VARCHAR2(200),
  date_published DATE,
  page_count INTEGER);

INSERT INTO BOOK VALUES (
   '1-56592-335-9', 'ORACLE PL/SQL PROGRAMMING', 'GENERAL PL/SQL REFERENCE',
   'FEUERSTEIN, STEVEN AND BILL PRIBYL',
   '23-SEP-95',
   1020);

INSERT INTO BOOK VALUES (
   '1-56592-238-7', 'ADVANCED ORACLE PL/SQL PROGRAMMING PROGRAMMING WITH PACKAGES', 
   'FOCUS ON PACKAGE CONSTRUCTION',
   'FEUERSTEIN, STEVEN',
   '23-OCT-96',
   687);

INSERT INTO BOOK VALUES (
   '1-56592-375-8', 'ORACLE BUILT-IN PACKAGES', 
   'FOCUS ON BUILT-IN PACKAGES',
   'FEUERSTEIN, STEVEN, CHARLES DYE AND JOHN BERESNIEWICZ',
   '01-APR-98',
   952);

INSERT INTO BOOK VALUES (
   '1-56592-456-8', 'ORACLE PL/SQL BUILT-INS POCKET REFERENCE', 
   'QUICK REFERENCE TO THE PL/SQL BUILT-INS',
   'FEUERSTEIN, STEVEN, JOHN BERESNIEWICZ AND CHIP DAWES',
   '01-OCT-98',
   78);

INSERT INTO BOOK VALUES (
   '1-56592-674-9', 'ORACLE PL/SQL DEVELOPER''S WORKBOOK', 
   'QUICK REFERENCE TO THE PL/SQL LANGUAGE',
   'FEUERSTEIN, STEVEN WITH ANDREW ODEWAHN',
   TO_DATE ('01-MAY-00', 'DD-MON-RR'),
   588);

INSERT INTO BOOK VALUES (
   '1-56592-675-7', 'ORACLE PL/SQL PROGRAMMING GUIDE TO ORACLE8I FEATURES', 
   'GUIDE TO NEW PL/SQL FEATURES IN ORACLE8I',
   'FEUERSTEIN, STEVEN',
   TO_DATE ('01-OCT-99', 'DD-MON-RR'),
   264);
   
INSERT INTO BOOK VALUES (
   '1-56592-457-6', 'ORACLE PL/SQL LANGUAGE POCKET REFERENCE ', 
   'QUICK REFERENCE TO THE PL/SQL LANGUAGE',
   'FEUERSTEIN, STEVEN, BILL PRIBYL AND CHIP DAWES',
   '01-APR-99',
   99);

INSERT INTO BOOK VALUES (
   '1-56592-849-0', 'THE ORACLE PL/SQL CD BOOKSHELF', 
   'CD-BASED COLLECTION OF MOST OF THE O''REILLY PL/SQL BOOKS',
   'FEUERSTEIN, STEVEN, ET AL',
   TO_DATE ('01-JUL-00', 'DD-MON-RR'),
   285);
   
COMMIT;