COLUMN LAST_NAME HEADING 'LAST NAME'
COLUMN SALARY HEADING 'MONTHLY SALARY' FORMAT $99,999
COLUMN COMMISSION_PCT HEADING 'COMMISSION %' FORMAT 90.90

SELECT LAST_NAME, SALARY, COMMISSION_PCT
  FROM EMP_DETAILS_VIEW
 WHERE JOB_ID='SA_MAN';
