DECLARE
   v1 PLS_INTEGER;
   v2 NATURAL;
   v3 NATURALN := 0;
   v4 POSITIVE;
   v5 POSITIVEN := 1;
   v6 SIGNTYPE;
--   v7 SIMPLE_INTEGER;
   v8 BINARY_FLOAT;
   v9 BINARY_DOUBLE;
   v10 BINARY_INTEGER;
--   v11 BINARY_FLOAT_NAN;
--   v12 BINARY_FLOAT_INFINITY;
--   v13 BINARY_FLOAT_MAX_NORMAL;
--   v14 BINARY_FLOAT_MIN_NORMAL;
--   v15 BINARY_FLOAT_MAX_SUBNORMAL;
--   v16 BINARY_FLOAT_MIN_SUBNORMAL;
--   v17 BINARY_DOUBLE_NAN;
--   v18 BINARY_DOUBLE_INFINITY;
--   v19 BINARY_DOUBLE_MAX_NORMAL;
--   v20 BINARY_DOUBLE_MIN_NORMAL;
--   v21 BINARY_DOUBLE_MAX_SUBNORMAL;
--   v22 BINARY_DOUBLE_MIN_SUBNORMAL;
BEGIN
   NULL;
END;
.
/
